[tools]
go = "1.26.0"
air = "1.64.5"
"aqua:golang-migrate/migrate" = "4.19.1"
sqlc = "v1.30.0"
oapi-codegen = "v2.6.0"
protoc = "34.0"
protoc-gen-go = "1.36.11"
protoc-gen-go-grpc = "1.6.1"
fzf = "latest"
ripgrep = "latest"

[tasks.build]
depends = ['sqlc-generate', 'openapi-generate', 'grpc-generate']
run = 'go build ./...'

[tasks.test]
description = "Runs all the test in repo"
usage = '''
flag "--count <count>" help="How many times to run tests" default="1"
'''
depends = ['test-setup']
run = 'go test -v ${usage_count:+-count ${usage_count}} ./...'

[tasks.test-setup]
description = "Common test setup."
hide = true
depends = ['build']
run = [
	'go build -o ./tmp/testing-guest ./test/testing-guest',
	'sqlc -f ./test/test_utils/sqlc.yaml compile',
	'sqlc -f ./test/test_utils/sqlc.yaml generate',
]

[tasks.test-by-name]
description = "Runs selected test function."
depends = ['test-setup']
run = '''
TEST_NAME=$(rg -o 'func Test.*\(t \*testing.T.*\)' | sed -e 's/func\s\(Test.*\)(t\s\*testing\.T)/ \1/g' | fzf --prompt 'Test to run: ' | rg -o 'Test.*')
go test -run $TEST_NAME -v ./...
'''

[tasks.add-migration]
description = "Adds new migration"
usage = '''
arg "<migration_name>" help="The name of the migration"
'''
run = 'migrate create -dir ./db/migrations -ext sql ${usage_migration_name}'

[tasks.sqlc-generate]
description = "Runs sqlc to generate Go code for queries"
run = [
	'sqlc -f ./pkg/commander/sqlc.yaml compile',
	'sqlc -f ./pkg/commander/sqlc.yaml generate'
]

[tasks.openapi-generate]
description = "Generates code from openapi specs in ./api/"
run = [
	'oapi-codegen --config ./pkg/api/common-api-codegen.yaml ./api/common.yaml',
	'oapi-codegen --config ./pkg/api/commander-api-codegen.yaml ./api/commander-openapi.yaml',
	'oapi-codegen --config ./pkg/api/commander-api-client-codegen.yaml ./api/commander-openapi.yaml',
]

[tasks.grpc-generate]
description = "Generates code from proto files"
run = [
	'protoc --go_out=paths=source_relative:. --go-grpc_out=paths=source_relative:. pkg/guest/guest.proto',
	'protoc --go_out=paths=source_relative:. --go-grpc_out=paths=source_relative:. pkg/runner/runner.proto',
	'protoc --go_out=paths=source_relative:. --go-grpc_out=paths=source_relative:. pkg/commander/commander.proto'
]
