app_name: commander
env: PROD
host: 0.0.0.0
http_port: "42069"
grpc_port: "42070"
db_uri: /data/commander.db
func_storage_root: /data/functions
runner_heartbeat_poll: 250ms
runner_overloaded_queue_size: 256
instance_overloaded_queue_size: 8
