FROM golang:1.26.0-alpine AS builder

WORKDIR /src

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY pkg ./pkg
COPY cmd ./cmd

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/runner ./cmd/runner

FROM alpine:3.21

RUN apk add --no-cache ca-certificates gcompat

COPY --from=builder /out/runner /runner

ENTRYPOINT ["/runner"]
