FROM golang:1.26.0-alpine AS builder

WORKDIR /src

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY pkg ./pkg
COPY cmd ./cmd
COPY api ./api

RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/commander ./cmd/commander

FROM scratch

COPY --from=builder /out/commander /commander

ENTRYPOINT ["/commander"]
