AppName: gateway
Env: PROD
Address: 0.0.0.0:8080
CommanderAddr: commander:42070
CommanderClientMonitoringOpts:
  Env: PROD
  AppName: gateway
RunnerClientMonitoringOpts:
  Env: PROD
  AppName: gateway
