app_name: gateway
env: PROD
address: 0.0.0.0:8080
commander_addr: commander:42070
commander_client_monitoring_opts:
  env: PROD
  app_name: gateway
runner_client_monitoring_opts:
  env: PROD
  app_name: gateway
