AppName: runner-1
CommitHash: local-test
Env: PROD
Addr: runner-1:42071
CommanderHost: commander
CommanderHttpPort: "42069"
CommanderGrpcPort: "42070"
InstanceShutdownAfter: 10m
InstanceGracePeriod: 1s
FuncStorageRoot: /data/functions
