syntax = "proto3";

package commander;

option go_package = "github.com/Nesquiko/servermore/pkg/commander/grpc";

message HeartbeatRequest {}
message HeartbeatResponse {}

message RunnerPingResponse {}

message RegisterRunnerRequest {
  string addr = 1;
}

message RegisterRunnerResponse {
  int64 runner_id = 1;
}

message RouteFunctionRequest {
  string function_id = 1;
}

message RouteFunctionResponse {
  string runner_addr = 1;
  string instance_id = 2;
}

service Commander {
  rpc Heartbeat(HeartbeatRequest) returns (HeartbeatResponse) {}

  rpc RegisterRunner(RegisterRunnerRequest) returns (RegisterRunnerResponse) {}

  rpc RouteFunction(RouteFunctionRequest) returns (RouteFunctionResponse) {}
}
